print('     __     ')
print('    /  \\    ')
print('   /    \\   ')
print('  /      \\  ')
print(' /        \\ ')
print('/          \\')
print('|Hello, world|') #Выводим приветствие
print('\           /')
print(' \         / ')
print('  \       /  ')
print('   \     /   ')
print('    \___/    ')
print(123)
